# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 599e6f5f232f38f2651a85d9c31077d31627eb89ea3c8578d758d01f3e7282582d3f31f47e544eef199d83965c93a89a90253615befb4e4be4d5d86dc0e54349

test:
  secret_key_base: c3a54061cde3b8240dbd47dd3bff211a3c92f06589a5f002a788706a3906d7ed3dad3d70c5f4c5a9f45d6182710056d6a765b604fbf8dd3d815737717a28ad3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
